import classNames from "classnames/bind";
import styles from "./layout.module.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Project Search",
  description: "Generated by create next app",
};

const cx = classNames.bind(styles);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body>
        <div className={cx("container")}>
          <header className={cx("header")}>
            <Image
              src={"/images/icon/logo.png"}
              alt="로고"
              width={40}
              height={40}
            />
            <span className={cx("title")}>
              <b>P</b>roject <b>S</b>earch
            </span>

            <div className={"btn_container"}>
              <Link className="btn img" href={"/mypage"}>
                <Image
                  src={"/images/icon/plus_white.png"}
                  alt="프로젝트 만들기"
                  width={20}
                  height={20}
                />
              </Link>
              <Link className="btn" href={"/mypage"}>
                My
              </Link>
              <button className="btn">로그인</button>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
